"use client";

import { useState } from "react";
import Link from "next/link";
import type { QRPayload } from "./QRShare";

function isValidPayload(obj: unknown): obj is QRPayload {
  if (typeof obj !== "object" || obj === null) return false;
  const p = obj as Record<string, unknown>;
  return (
    p.v === 1 &&
    typeof p.lat === "number" &&
    typeof p.lng === "number" &&
    typeof p.ts === "number" &&
    (p.type === "text" || p.type === "photo" || p.type === "voice")
  );
}

interface ImportedSignal {
  id: string;
  locationName: string;
  claim: string;
  credibilityScore: number;
  severity: number;
}

export default function ImportReport({ encoded }: { encoded: string | null }) {
  const [status, setStatus]           = useState<"idle" | "importing" | "done" | "error">("idle");
  const [importedSignal, setImported] = useState<ImportedSignal | null>(null);
  const [errorMsg, setErrorMsg]       = useState<string | null>(null);

  // Decode and validate the payload
  let payload: QRPayload | null = null;
  let decodeError: string | null = null;

  if (!encoded) {
    decodeError = "No report data found in this link.";
  } else {
    try {
      const parsed: unknown = JSON.parse(atob(encoded));
      if (isValidPayload(parsed)) {
        payload = parsed;
      } else {
        decodeError = "This QR code doesn't contain a valid GroundTruth report.";
      }
    } catch {
      decodeError = "Could not read the report data — the link may be corrupted.";
    }
  }

  async function saveReport() {
    if (!payload) return;
    setStatus("importing");
    setErrorMsg(null);
    try {
      const res = await fetch("/api/reports", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          type: payload.type,
          content: payload.content ?? "",
          latitude: payload.lat,
          longitude: payload.lng,
        }),
      });
      if (!res.ok) throw new Error(`Server ${res.status}`);
      const data = (await res.json()) as { signal: ImportedSignal };
      setImported(data.signal);
      setStatus("done");
    } catch (err) {
      setErrorMsg(err instanceof Error ? err.message : "Import failed. Try again.");
      setStatus("error");
    }
  }

  // ── Invalid / missing data ────────────────────────────────────────────────
  if (decodeError) {
    return (
      <div className="bg-rose-50 border border-rose-200 rounded-2xl px-5 py-6 text-center space-y-3">
        <p className="text-sm font-semibold text-rose-700">{decodeError}</p>
        <p className="text-xs text-rose-600">
          Make sure you scanned a QR code generated by GroundTruth.
        </p>
        <Link href="/report"
          className="inline-block mt-2 text-xs font-semibold text-teal-700 underline">
          Go to Report page
        </Link>
      </div>
    );
  }

  // ── Success ───────────────────────────────────────────────────────────────
  if (status === "done" && importedSignal) {
    return (
      <div className="space-y-4">
        <div className="bg-teal-50 border border-teal-200 rounded-2xl px-5 py-4 flex items-center gap-3">
          <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={2.2}
            strokeLinecap="round" strokeLinejoin="round" className="w-5 h-5 text-teal-600 flex-shrink-0">
            <path d="M5 13l4 4L19 7" />
          </svg>
          <div>
            <p className="text-sm font-semibold text-teal-800">Report saved to this device</p>
            {importedSignal.locationName && (
              <p className="text-xs text-teal-700 mt-0.5">{importedSignal.locationName}</p>
            )}
          </div>
        </div>

        {importedSignal.claim && (
          <div className="bg-white border border-slate-200 rounded-2xl px-4 py-3">
            <p className="text-[11px] font-semibold text-slate-400 uppercase tracking-wider mb-1">
              AI extracted claim
            </p>
            <p className="text-sm text-slate-700 italic leading-relaxed">
              &ldquo;{importedSignal.claim}&rdquo;
            </p>
          </div>
        )}

        <div className="flex gap-2">
          <div className="flex-1 bg-teal-50 border border-teal-100 rounded-xl px-3.5 py-2.5 flex items-center justify-between">
            <span className="text-xs text-teal-700">Credibility</span>
            <span className="text-sm font-bold text-teal-700">
              {Math.round(importedSignal.credibilityScore * 100)}%
            </span>
          </div>
          <div className="flex-1 bg-slate-50 border border-slate-100 rounded-xl px-3.5 py-2.5 flex items-center justify-between">
            <span className="text-xs text-slate-600">Severity</span>
            <span className="text-sm font-bold text-slate-700">
              {importedSignal.severity}/5
            </span>
          </div>
        </div>

        <Link
          href="/"
          className="block w-full py-3 rounded-xl text-sm font-semibold bg-teal-600 text-white hover:bg-teal-700 transition-colors text-center"
        >
          View dashboard
        </Link>
      </div>
    );
  }

  // ── Preview + import ─────────────────────────────────────────────────────
  const typeLabel =
    payload!.type === "photo" ? "Photo report" :
    payload!.type === "voice" ? "Voice report" : "Text report";

  const reportDate = new Date(payload!.ts).toLocaleString(undefined, {
    month: "short", day: "numeric", hour: "2-digit", minute: "2-digit",
  });

  return (
    <div className="space-y-4">
      {/* What this is */}
      <div className="bg-white border border-slate-200 rounded-2xl px-4 py-4 space-y-3">
        <div className="flex items-center justify-between">
          <p className="text-sm font-semibold text-slate-900">{typeLabel}</p>
          <span className="text-xs text-slate-400">{reportDate}</span>
        </div>

        <div className="flex items-center gap-2 text-xs text-slate-500">
          <svg viewBox="0 0 24 24" fill="currentColor" className="w-3.5 h-3.5 text-teal-500 flex-shrink-0">
            <path d="M12 2C8.13 2 5 5.13 5 9c0 5.25 7 13 7 13s7-7.75 7-13c0-3.87-3.13-7-7-7zm0 9.5c-1.38 0-2.5-1.12-2.5-2.5s1.12-2.5 2.5-2.5 2.5 1.12 2.5 2.5-1.12 2.5-2.5 2.5z" />
          </svg>
          <span className="font-mono">
            {payload!.lat.toFixed(5)}, {payload!.lng.toFixed(5)}
          </span>
        </div>

        {payload!.content && (
          <div className="bg-slate-50 rounded-xl px-3.5 py-3">
            <p className="text-sm text-slate-700 leading-relaxed italic">
              &ldquo;{payload!.content}&rdquo;
            </p>
          </div>
        )}
      </div>

      {/* Context */}
      <p className="text-xs text-slate-500 px-0.5">
        Saving this adds the report to your local database. Gemma will analyze it
        and it will appear on your dashboard — no internet required.
      </p>

      {/* Error */}
      {status === "error" && (
        <p className="text-xs text-rose-600 font-medium">{errorMsg}</p>
      )}

      {/* Action */}
      <button
        onClick={() => void saveReport()}
        disabled={status === "importing"}
        className="w-full py-3 rounded-xl text-sm font-semibold bg-teal-600 text-white hover:bg-teal-700 disabled:opacity-50 disabled:cursor-wait transition-colors"
      >
        {status === "importing" ? "Saving…" : "Save to this device"}
      </button>

      <Link
        href="/"
        className="block text-center text-xs text-slate-400 hover:text-teal-600 transition-colors"
      >
        Go to dashboard without saving
      </Link>
    </div>
  );
}
